# Generated by Django 4.1.7 on 2023-03-28 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vk_info', '0001_initial'),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Имя')),
                ('surname', models.CharField(max_length=128, verbose_name='Фамилия')),
                ('second_name', models.CharField(max_length=128, verbose_name='Отчество')),
                ('age', models.PositiveSmallIntegerField(max_length=3, verbose_name='Возраст')),
                ('telephone_number', models.CharField(max_length=12, null=True, unique=True, verbose_name='Телефонный номер')),
                ('email', models.CharField(max_length=128, null=True, unique=True, verbose_name='Почта')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('slug', models.SlugField(max_length=128, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Информация о клиенте',
                'verbose_name_plural': 'Информация о клиенте',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, null=True, verbose_name='Название профиля')),
                ('slug', models.SlugField(default='', max_length=128, unique=True, verbose_name='URL')),
                ('analytics', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='analytics.analytics', verbose_name='ID страницы аналитики')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='profiles.client', verbose_name='ID клиента')),
                ('vk_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='vk_info.vkinfo', verbose_name='ID страницы ВК')),
            ],
            options={
                'verbose_name': 'Информация о профиле',
                'verbose_name_plural': 'Информация о профиле',
            },
        ),
    ]
