# Generated by Django 4.1.7 on 2023-04-25 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('vk_info', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='profiles.profile', verbose_name='Ссылка на профиль'),
        ),
        migrations.AlterField(
            model_name='client',
            name='age',
            field=models.PositiveSmallIntegerField(verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='analytics',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='analytics.analytics', verbose_name='Название страницы аналитики'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='profiles.client', verbose_name='ФИО клиента'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='vk_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='vk_info.vkinfo', verbose_name='URL страницы ВК'),
        ),
    ]
