# Generated by Django 4.1.7 on 2023-03-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('slug', models.SlugField(max_length=128, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Анализ',
                'verbose_name_plural': 'Анализ',
            },
        ),
    ]
