# Generated by Django 4.1.7 on 2023-05-03 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grammar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('future_verbs', models.PositiveIntegerField(verbose_name='Количество глаголов в будущем времени')),
                ('present_verbs', models.PositiveIntegerField(verbose_name='Количество глаголов в настоящем времени')),
                ('past_verbs', models.PositiveIntegerField(verbose_name='Количество глаголов в прошедшем времени')),
                ('perfect_verbs', models.PositiveIntegerField(verbose_name='Количество глаголов совершенного вида')),
                ('continuous_verbs', models.PositiveIntegerField(verbose_name='Количество глаголов несовершенного вида')),
                ('subjunctive_verbs', models.PositiveIntegerField(verbose_name='Количество глаголов в форме сослагательного наклонения')),
                ('diminutive_morphemes', models.PositiveIntegerField(verbose_name='Количество уменьшительно-ласкательном морфем')),
                ('active_voice', models.PositiveIntegerField(verbose_name='Количество глаголов в активном залоге')),
                ('passive_voice', models.PositiveIntegerField(verbose_name='Количество глаголов в пассивном залоге')),
                ('slug', models.SlugField(max_length=128, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Грамматика',
                'verbose_name_plural': 'Грамматика',
            },
        ),
        migrations.CreateModel(
            name='Syntax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('questions', models.PositiveIntegerField(verbose_name='Количество вопросительных предложений')),
                ('comparative_turnovers', models.PositiveIntegerField(verbose_name='Количество сравнительных оборотов')),
                ('slug', models.SlugField(max_length=128, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Синтаксис',
                'verbose_name_plural': 'Синтаксис',
            },
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('nouns', models.PositiveIntegerField(verbose_name='Количество существительных')),
                ('verbs', models.PositiveIntegerField(verbose_name='Количество глаголов')),
                ('adjectives', models.PositiveIntegerField(verbose_name='Количество прилагательных')),
                ('professional_vocabulary', models.PositiveIntegerField(verbose_name='Количество профессиональной лексики')),
                ('expressive_vocabulary', models.PositiveIntegerField(verbose_name='Количество экспрессивной лексики')),
                ('diminutive_words', models.PositiveIntegerField(verbose_name='Количество уменьшительно-ласкательных слов')),
                ('personal_pronouns', models.PositiveIntegerField(verbose_name='Количество личных местоимений')),
                ('numerals', models.PositiveIntegerField(verbose_name='Количество числительных')),
                ('slug', models.SlugField(max_length=128, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Лексика',
                'verbose_name_plural': 'Лексика',
            },
        ),
        migrations.AlterField(
            model_name='analytics',
            name='slug',
            field=models.SlugField(max_length=128, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.CreateModel(
            name='IStatements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст высказывания')),
                ('syntax', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='analytics.syntax', verbose_name='Ссылка на таблицу синтаксиса')),
            ],
        ),
        migrations.AddField(
            model_name='analytics',
            name='grammar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='analytics.grammar', verbose_name='Ссылка на таблицу грамматики'),
        ),
        migrations.AddField(
            model_name='analytics',
            name='syntax',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='analytics.syntax', verbose_name='Ссылка на таблицу синтаксиса'),
        ),
        migrations.AddField(
            model_name='analytics',
            name='vocabulary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='analytics.vocabulary', verbose_name='Ссылка на таблицу лексики'),
        ),
    ]
