# Generated by Django 4.1.7 on 2023-03-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VkInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_url', models.CharField(max_length=128, verbose_name='ВК ссылка')),
                ('client_name', models.CharField(max_length=128, verbose_name='Имя в профиле ВК')),
                ('client_surname', models.CharField(max_length=128, verbose_name='Фамилия в профиле ВК')),
                ('nickname', models.CharField(max_length=128, null=True, unique=True, verbose_name='Никнейм в профиле ВК')),
                ('telephone_number', models.CharField(max_length=12, null=True, verbose_name='Телефонный номер')),
                ('birth_date', models.DateField(null=True, verbose_name='Дата рождения')),
                ('sex', models.CharField(max_length=10, null=True, verbose_name='Пол')),
                ('location', models.CharField(max_length=128, null=True, verbose_name='Местоположение')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('slug', models.SlugField(default='', max_length=128, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Информация из ВК',
                'verbose_name_plural': 'Информация из ВК',
            },
        ),
    ]
