# Generated by Django 4.1.7 on 2023-04-25 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_vk_info'),
        ('vk_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vkinfo',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='profiles.profile', verbose_name='Ссылка на профиль'),
        ),
    ]
